name: Bug Report
description: Report a bug to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Bug Description
      description: What is the bug?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the issue
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true
