name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["feature"]
body:
  - type: textarea
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe the feature you want
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Any extra info, mockups, or references?
    validations:
      required: false
